### ISSUE TITLE
Use ol3-cesium

### ISSUE THREAD

**Issue by richa2008** [openlayers/ol3-cesium#190]
Hi,
I am trying to use ol3-cesium on windows7.How to do that.Please help.Thanks.

**Comment by gberaudo** [comment]
You have two choices:
- either use an already compiled version from https://github.com/openlayers/ol3-cesium/releases
- or compile the library yourself.

In order to compile the library you will need to install some dependencies, see README.md.
I think you are the first one wanting to do it on Windows.

The easy way would be to install an Ubuntu VM however there is certainly a native way.
Feel free to reopen and share your findings.
