### ISSUE TITLE
getZoom() returns undefined when in 3d

### ISSUE THREAD

**Issue by jmgomezpoveda** [openlayers/ol3-cesium#343]
When using ol3-cesium and the map is in 3d mode, calling map.getView().getZoom() returns undefined. This might affect setZoom as well.

I understand we are in a 3d world, so there are no z-levels as in the tiled maps. On the other hand, Google Maps calculates a z-equivalent when coming back grom 3d to 2d.

I have created a question in stackoverflow (http://stackoverflow.com/questions/36544209/converting-altitude-to-z-level-and-vice-versa) to try to calculate the equivalence between altitude and z.

Might it make sense for ol3-cesium to incorporate such conversion into getZoom and setZoom when in 3d mode?

**Comment by gberaudo** [comment]
No, that is not related to 3D. It is simply that the resolution of the 2D map is not equal
to a constrained resolution (see ol.View.getZoom implementation).

I think it would make sense to have a method to return the closest resolution in ol.View and also an helper to get the zoom level of a resolution (exactly the same as ol.View.getZoom, but working on a passed resolution instead of the result of `this.getResolution()`.

Then the user would be able to snap to a pixel perfect resolution when needed.

**Comment by jmgomezpoveda** [comment]
As a workaround, I have created an approximate altitudeToZoom function: http://stackoverflow.com/a/37142662/1816603

```
function altitudeToZoom(altitude) {
    var A = 40487.57;
    var B = 0.00007096758;
    var C = 91610.74;
    var D = -40467.74;

    return D+(A-D)/(1+Math.pow(altitude/C, B));
}
```

**Comment by topwood** [comment]
+1

**Comment by gberaudo** [comment]
This should be implemented in OpenLayers so I am closing it.
